flaskr/__init__.py
import os
from flask import Flask, render_template, g
from flaskr.service.session import load_from_session
from werkzeug.exceptions import HTTPException


def create_app(test_config=None) -> Flask:
    app = Flask(__name__, instance_relative_config=True)
    app.config.from_mapping(
        SECRET_KEY='dev',
        DATABASE=os.path.join(app.instance_path, 'flaskr.sqlite')
    )

    if test_config is None:
        # load the instance config, if it exists, when not testing
        app.config.from_pyfile('config.py', silent=True)
    else:
        # load the test config if passed in
        app.config.from_mapping(test_config)

    try:
        os.makedirs(app.instance_path)
    except OSError:
        pass

    from .blueprint import api
    app.register_blueprint(api.bp)

    from .blueprint import auth
    app.register_blueprint(auth.bp)

    @app.before_request
    def load_user():
        load_from_session()

    @app.route('/hello')
    def hello():
        return 'Hello, World!'

    @app.route('/')
    def index():
        return render_template('index.html')

    @app.errorhandler(HTTPException)
    def handle_exception(e: HTTPException):
        g.error = e
        return render_template('error.html'), e.code

    return app

flaskr/blueprint/auth.py
from flask import Blueprint, request, redirect, flash, render_template
import flaskr.service.auth as auth_service
import flaskr.service.session as session_service

bp = Blueprint('auth', __name__, url_prefix='/')


@bp.route('/login', methods=['GET', 'POST'])
def login():
    if session_service.is_logged_in():
        return redirect('/')
    if request.method == 'POST':
        acc_or_msg = auth_service.login(request.form)
        if not isinstance(acc_or_msg, str):
            session_service.set_session(acc_or_msg)
            return redirect('/')
        flash(acc_or_msg)

    return render_template('login.html')


@bp.route('/register', methods=['GET', 'POST'])
def register():
    if session_service.is_logged_in():
        return redirect('/')
    if request.method == 'POST':
        acc_or_msg = auth_service.register(request.form)
        if not isinstance(acc_or_msg, str):
            session_service.set_session(acc_or_msg)
            return redirect('/')
        flash(acc_or_msg)

    return render_template('register.html')


@bp.route('/logout')
def logout():
    session_service.clear_session()
    return redirect('/')

flaskr/service/auth.py
import flaskr.repo.user as repo
from flaskr.model.user import UserModel
from flaskr.util.validator import Validator
from werkzeug.security import check_password_hash, generate_password_hash


def login(data: dict[str, str]):
    msg = Validator(data).set_field('username').is_not_empty().set_field(
        'password').is_not_empty().msg()
    if msg is not None:
        return msg
    user_data = UserModel(**data)
    user = repo.get_one(username=user_data.username)
    if user is None or not check_password_hash(user.password, user_data.password):
        return 'Incorrect username / password!'
    return user


def register(data: dict[str, str]):
    msg = Validator(data).set_field('username').is_not_empty().is_alphanumeric().set_field(
        'password').is_not_empty().set_field('email').is_not_empty().is_email().msg()
    if msg is not None:
        return msg
    user_data = UserModel(**data)
    user_data.password = generate_password_hash(user_data.password)
    user = repo.insert(user_data)
    if user is None:
        return 'Account already exists!'
    return user

flaskr/templates/api.html
{% extends 'base.html' %} 

{% block title %} 
  Simple Auth - API
{% endblock %} 

{% block link %}
  <link rel="stylesheet" href="{{ url_for('static', filename='api.css') }}" />
{% endblock %} 

{% block body %}
  <div class="container">
    {% if g.users %}
        <table>
            <caption>User Count : {{ g.users|length }}</caption>
            <thead>
                <tr>
                    <th>ID</th>
                    <th>Username</th>
                    <th>Email</th>
                </tr>
            </thead>
            <tbody>
                {% for user in g.users %}
                    <tr>
                        <td>{{ user.id }}</td>
                        <td>{{ user.username }}</td>
                        <td>{{ user.email }}</td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>

        
    {% endif %}
    
  </div>
{% endblock %}

flaskr/templates/base.html
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>{% block title %} {% endblock %}</title>
    <link
      rel="stylesheet"
      href="{{ url_for('static', filename='base.css') }}"
    />
    {% block link %} {% endblock %}
  </head>

  <body>
    {% block body %} {% endblock %}
  </body>
</html>

flaskr/templates/error.html
{% extends 'base.html' %} 

{% block title %} 
  Oops {% if g.error %} - {{ g.error.name }} {% endif %} 
{% endblock %} 

{% block link %}
  <link rel="stylesheet" href="{{ url_for('static', filename='error.css') }}" />
{% endblock %} 

{% block body %}
  <div class="container">
    <h1 class="title">Something wrong!</h1>
    <p class="description">
      {% if g.error %} 
        {{ g.error.description }}
        </br>
        (Code : {{ g.error.code }}) 
      {% else %} Please try again later. 
      {% endif %}
    </p>
  </div>
{% endblock %}

flaskr/templates/index.html
{% extends 'base.html' %} 

{% block title %} Simple Auth {% endblock %} 

{% block link %}
  <link rel="stylesheet" href="{{ url_for('static', filename='index.css') }}" />
{% endblock %} 

{% block body %}
  <div class="container">
    <h1 class="title">
      {% if g.user %} Hello, {{g.user.username}} 
      {% else %} Simple Auth 
      {% endif %}
    </h1>
    {% if g.user %}
      <div class="profile">
        <h4>Id       : {{ g.user.id }}</h3>
        <h4>Username : {{ g.user.username }}</h4>
        <h4>Email    : {{ g.user.email }}</h4>
      </div>
    {% endif %}
    <div class="actions">
      {% if g.user %}
        <a href="{{ url_for('auth.logout') }}" class="btn">Logout</a>
      {% else %}
        <a href="{{ url_for('auth.login') }}" class="btn">Login</a>
        <a href="{{ url_for('auth.register') }}" class="btn">Register</a>
      {% endif %}
    </div>
  </div>
{% endblock %}

flaskr/templates/login.html
{% extends 'base.html' %} 

{% block title %} Login {% endblock %} 

{% block link %}
  <link rel="stylesheet" href="{{ url_for('static', filename='auth.css') }}" />
{% endblock %} 

{% block body %}
  <div class="container">
    <h1 class="title">Login</h1>
    {% for message in get_flashed_messages() %}
      <div class="msg">{{ message }}</div>
    {% endfor %}
    <form action="{{ url_for('auth.login') }}" method="post">
      <input
        id="username"
        name="username"
        type="text"
        required
        placeholder="Enter your username"
        class="textbox"
      />
      <input
        id="password"
        name="password"
        type="password"
        required
        placeholder="Enter your password"
        class="textbox"
      />
      <input type="submit" value="Sign In" class="btn" />
    </form>
  </div>
{% endblock %}

flaskr/templates/register.html
{% extends 'base.html' %} 

{% block title %} Register {% endblock %} 

{% block link %}
  <link rel="stylesheet" href="{{ url_for('static', filename='auth.css') }}" />
{% endblock %} 

{% block body %}
  <div class="container">
    <h1 class="title">Register</h1>
    {% for message in get_flashed_messages() %}
      <div class="msg">{{ message }}</div>
    {% endfor %}
    <form action="{{ url_for('auth.register') }}" method="post">
      <input
        id="username"
        name="username"
        type="text"
        required
        placeholder="Enter your username"
        class="textbox"
      />
      <input
        id="password"
        name="password"
        type="password"
        required
        placeholder="Enter your password"
        class="textbox"
      />
      <input
        id="email"
        name="email"
        type="email"
        required
        placeholder="Enter your email"
        class="textbox"
      />
      <input type="submit" value="Sign Up" class="btn" />
    </form>
  </div>
{% endblock %}